### ISSUE TITLE
Stack trace shown on reconnect

### ISSUE THREAD

**Issue by githansvp** [sara-nl/BeeHub#266]
On navigating to beehub.nl/systems I get a stack trace:

HTTP/1.1 500 Internal Server Error
exception 'MongoConnectionException' with message 'Failed to connect to: localhost:27017: Remote server has closed the connection' in /var/www/BeeHub/src/BeeHub.php:477
Stack trace:
#0 /var/www/BeeHub/src/BeeHub.php(477): MongoClient->__construct('mongodb://local...')
#1 /var/www/BeeHub/src/BeeHub_MongoResource.php(65): BeeHub::getNoSQL()
#2 /var/www/BeeHub/src/BeeHub_Resource.php(123): BeeHub_MongoResource->init_props()
#3 /var/www/BeeHub/src/BeeHub_Resource.php(265): BeeHub_Resource->user_prop('DAV: owner')
#4 /var/www/BeeHub/src/BeeHub_Resource.php(233): BeeHub_Resource->user_prop_owner()
#5 /var/www/BeeHub/vendor/pieterb/webdav-php/lib/DAVACL_Resource.php(61): BeeHub_Resource->user_prop_acl()
#6 /var/www/BeeHub/vendor/pieterb/webdav-php/lib/DAVACL_Resource.php(162): DAVACL_Resource->effective_acl()
#7 /var/www/BeeHub/src/BeeHub_Resource.php(81): DAVACL_Resource->assert('http://beehub.n...')
#8 /var/www/BeeHub/vendor/pieterb/webdav-php/lib/DAV_Request.php(351): BeeHub_Resource->isVisible()
#9 /var/www/BeeHub/public/index.php(52): DAV_Request->handleRequest()
#10 {main}

Second attempt shows web interface correctly.

**Comment by niekbosch** [comment]
Was already fixed, but not rolled out to production environment yet
